# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q2sXNL33DszzkUKUdYzLSLUR72HfspIq
"""

# TensorFlow
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

import kagglehub

# Download latest version
path = kagglehub.dataset_download("shuvokumarbasak4004/world-flags-dataset-195")

print("Path to dataset files:", path)

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_data = train_datagen.flow_from_directory(
    "/kaggle/input/world-flags-dataset-195/data",
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_data = train_datagen.flow_from_directory(
    "/kaggle/input/world-flags-dataset-195/data",
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

print(train_data.class_indices)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
    MaxPooling2D(2, 2),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5),

    Dense(train_data.num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=5
)

model.save("/content/drive/MyDrive/final_flag_model.h5")

import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# ----- Load Model -----
model = load_model("/content/drive/MyDrive/final_flag_model.h5")

# ----- Class Labels -----
class_indices = {
    'Afghanistan': 0, 'Albania': 1, 'Algeria': 2, 'Andorra': 3, 'Angola': 4,
    'Antigua and Barbuda': 5, 'Argentina': 6, 'Armenia': 7, 'Australia': 8,
    'Austria': 9, 'Azerbaijan': 10, 'Bahamas': 11, 'Bahrain': 12, 'Bangladesh': 13,
    'Barbados': 14, 'Belarus': 15, 'Belgium': 16, 'Belize': 17, 'Benin': 18,
    'Bhutan': 19, 'Bolivia': 20, 'Bosnia and Herzegovina': 21, 'Botswana': 22,
    'Brazil': 23, 'Brunei': 24, 'Bulgaria': 25, 'Burkina Faso': 26, 'Burundi': 27,
    'CAR': 28, 'Cabo Verde': 29, 'Cambodia': 30, 'Cameroon': 31, 'Canada': 32,
    'Chad': 33, 'Chile': 34, 'China': 35, 'Colombia': 36, 'Comoros': 37,
    'Congo': 38, 'Costa Rica': 39, 'Croatia': 40, 'Cuba': 41, 'Cyprus': 42,
    'Czechia': 43, 'DPRK': 44, 'DRC': 45, 'Denmark': 46, 'Djibouti': 47,
    'Dominica': 48, 'Dominican Republic': 49, 'Ecuador': 50, 'Egypt': 51,
    'El Salvador': 52, 'Equatorial Guinea': 53, 'Eritrea': 54, 'Estonia': 55,
    'Eswatini': 56, 'Ethiopia': 57, 'Fiji': 58, 'Finland': 59, 'France': 60,
    'Gabon': 61, 'Gambia': 62, 'Georgia': 63, 'Germany': 64, 'Ghana': 65,
    'Greece': 66, 'Grenada': 67, 'Guatemala': 68, 'Guinea': 69, 'Guinea-Bissau': 70,
    'Guyana': 71, 'Haiti': 72, 'Holy See': 73, 'Honduras': 74, 'Hungary': 75,
    'Iceland': 76, 'India': 77, 'Indonesia': 78, 'Iran': 79, 'Iraq': 80,
    'Ireland': 81, 'Israel': 82, 'Italy': 83, 'Ivory Coast': 84, 'Jamaica': 85,
    'Japan': 86, 'Jordan': 87, 'Kazakhstan': 88, 'Kenya': 89, 'Kiribati': 90,
    'Kuwait': 91, 'Kyrgyzstan': 92, 'Laos': 93, 'Latvia': 94, 'Lebanon': 95,
    'Lesotho': 96, 'Liberia': 97, 'Libya': 98, 'Liechtenstein': 99, 'Lithuania': 100,
    'Luxembourg': 101, 'Madagascar': 102, 'Malawi': 103, 'Malaysia': 104,
    'Maldives': 105, 'Mali': 106, 'Malta': 107, 'Marshall Islands': 108,
    'Mauritania': 109, 'Mauritius': 110, 'Mexico': 111, 'Micronesia': 112,
    'Moldova': 113, 'Monaco': 114, 'Mongolia': 115, 'Montenegro': 116,
    'Morocco': 117, 'Mozambique': 118, 'Myanmar': 119, 'Namibia': 120,
    'Nauru': 121, 'Nepal': 122, 'Netherlands': 123, 'New Zealand': 124,
    'Nicaragua': 125, 'Niger': 126, 'Nigeria': 127, 'North Macedonia': 128,
    'Norway': 129, 'Oman': 130, 'Pakistan': 131, 'Palau': 132, 'Panama': 133,
    'Papua New Guinea': 134, 'Paraguay': 135, 'Peru': 136, 'Philippines': 137,
    'Poland': 138, 'Portugal': 139, 'Qatar': 140, 'Romania': 141, 'Russia': 142,
    'Rwanda': 143, 'Saint Kitts and Nevis': 144, 'Saint Lucia': 145, 'Samoa': 146,
    'San Marino': 147, 'Sao Tome and Principe': 148, 'Saudi Arabia': 149,
    'Senegal': 150, 'Serbia': 151, 'Seychelles': 152, 'Sierra Leone': 153,
    'Singapore': 154, 'Slovakia': 155, 'Slovenia': 156, 'Solomon Islands': 157,
    'Somalia': 158, 'South Africa': 159, 'South Korea': 160, 'South Sudan': 161,
    'Spain': 162, 'Sri Lanka': 163, 'St. Vincent Grenadines': 164,
    'State of Palestine': 165, 'Sudan': 166, 'Suriname': 167, 'Sweden': 168,
    'Switzerland': 169, 'Syria': 170, 'Tajikistan': 171, 'Tanzania': 172,
    'Thailand': 173, 'Timor-Leste': 174, 'Togo': 175, 'Tonga': 176,
    'Trinidad and Tobago': 177, 'Tunisia': 178, 'Turkey': 179, 'Turkmenistan': 180,
    'Tuvalu': 181, 'U.A.E': 182, 'U.K': 183, 'U.S': 184, 'Uganda': 185,
    'Ukraine': 186, 'Uruguay': 187, 'Uzbekistan': 188, 'Vanuatu': 189,
    'Venezuela': 190, 'Vietnam': 191, 'Yemen': 192, 'Zambia': 193, 'Zimbabwe': 194
}

# Convert dict → list such that index gives class name
class_names = [None] * len(class_indices)
for name, idx in class_indices.items():
    class_names[idx] = name


# ----- Prediction Function -----
def predict_flag(img_path, target_size=(224, 224)):
    img = image.load_img(img_path, target_size=target_size)
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    preds = model.predict(img_array)[0]

    # Best class selection
    class_index = np.argmax(preds)
    confidence = preds[class_index]

    print("Predicted Country:", class_names[class_index])
    print("Confidence:", round(float(confidence), 4))


# ----- Example -----
predict_flag("/ura.png")
predict_flag("/china.png")

import numpy as np
from tensorflow.keras.preprocessing import image

img_path = "/china.png"    # change this
img_size = (224, 224)   # change to your trained size

img = image.load_img(img_path, target_size=img_size)
img_array = image.img_to_array(img)
img_array = img_array / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)
print("Prediction:", prediction)

# ===============================
# 3. Upload image
# ===============================
from google.colab import files
from tensorflow.keras.preprocessing import image
import numpy as np

# uploaded = files.upload()
# img_path = list(uploaded.keys())[0]

image_path = "/china.png"   # ← replace this

# ===============================
# 4. Preprocess the image
# ===============================

img = image.load_img(img_path, target_size=(224, 224))  # change size if your model uses a different input size
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = img_array / 255.0    # normalize — change if your model uses different scaling

# ===============================
# 5. Predict
# ===============================

pred = model.predict(img_array)
print("Raw prediction output:", pred)

# If it's classification, find the class with max probability:
predicted_class = np.argmax(pred, axis=1)
print("Predicted Class Index:", predicted_class[0])

!pip install gradio

# class_names = [
#     'Afghanistan': 0, 'Albania': 1, 'Algeria': 2, 'Andorra': 3, 'Angola': 4,
#     'Antigua and Barbuda': 5, 'Argentina': 6, 'Armenia': 7, 'Australia': 8,
#     'Austria': 9, 'Azerbaijan': 10, 'Bahamas': 11, 'Bahrain': 12, 'Bangladesh': 13,
#     'Barbados': 14, 'Belarus': 15, 'Belgium': 16, 'Belize': 17, 'Benin': 18,
#     'Bhutan': 19, 'Bolivia': 20, 'Bosnia and Herzegovina': 21, 'Botswana': 22,
#     'Brazil': 23, 'Brunei': 24, 'Bulgaria': 25, 'Burkina Faso': 26, 'Burundi': 27,
#     'CAR': 28, 'Cabo Verde': 29, 'Cambodia': 30, 'Cameroon': 31, 'Canada': 32,
#     'Chad': 33, 'Chile': 34, 'China': 35, 'Colombia': 36, 'Comoros': 37,
#     'Congo': 38, 'Costa Rica': 39, 'Croatia': 40, 'Cuba': 41, 'Cyprus': 42,
#     'Czechia': 43, 'DPRK': 44, 'DRC': 45, 'Denmark': 46, 'Djibouti': 47,
#     'Dominica': 48, 'Dominican Republic': 49, 'Ecuador': 50, 'Egypt': 51,
#     'El Salvador': 52, 'Equatorial Guinea': 53, 'Eritrea': 54, 'Estonia': 55,
#     'Eswatini': 56, 'Ethiopia': 57, 'Fiji': 58, 'Finland': 59, 'France': 60,
#     'Gabon': 61, 'Gambia': 62, 'Georgia': 63, 'Germany': 64, 'Ghana': 65,
#     'Greece': 66, 'Grenada': 67, 'Guatemala': 68, 'Guinea': 69, 'Guinea-Bissau': 70,
#     'Guyana': 71, 'Haiti': 72, 'Holy See': 73, 'Honduras': 74, 'Hungary': 75,
#     'Iceland': 76, 'India': 77, 'Indonesia': 78, 'Iran': 79, 'Iraq': 80,
#     'Ireland': 81, 'Israel': 82, 'Italy': 83, 'Ivory Coast': 84, 'Jamaica': 85,
#     'Japan': 86, 'Jordan': 87, 'Kazakhstan': 88, 'Kenya': 89, 'Kiribati': 90,
#     'Kuwait': 91, 'Kyrgyzstan': 92, 'Laos': 93, 'Latvia': 94, 'Lebanon': 95,
#     'Lesotho': 96, 'Liberia': 97, 'Libya': 98, 'Liechtenstein': 99, 'Lithuania': 100,
#     'Luxembourg': 101, 'Madagascar': 102, 'Malawi': 103, 'Malaysia': 104,
#     'Maldives': 105, 'Mali': 106, 'Malta': 107, 'Marshall Islands': 108,
#     'Mauritania': 109, 'Mauritius': 110, 'Mexico': 111, 'Micronesia': 112,
#     'Moldova': 113, 'Monaco': 114, 'Mongolia': 115, 'Montenegro': 116,
#     'Morocco': 117, 'Mozambique': 118, 'Myanmar': 119, 'Namibia': 120,
#     'Nauru': 121, 'Nepal': 122, 'Netherlands': 123, 'New Zealand': 124,
#     'Nicaragua': 125, 'Niger': 126, 'Nigeria': 127, 'North Macedonia': 128,
#     'Norway': 129, 'Oman': 130, 'Pakistan': 131, 'Palau': 132, 'Panama': 133,
#     'Papua New Guinea': 134, 'Paraguay': 135, 'Peru': 136, 'Philippines': 137,
#     'Poland': 138, 'Portugal': 139, 'Qatar': 140, 'Romania': 141, 'Russia': 142,
#     'Rwanda': 143, 'Saint Kitts and Nevis': 144, 'Saint Lucia': 145, 'Samoa': 146,
#     'San Marino': 147, 'Sao Tome and Principe': 148, 'Saudi Arabia': 149,
#     'Senegal': 150, 'Serbia': 151, 'Seychelles': 152, 'Sierra Leone': 153,
#     'Singapore': 154, 'Slovakia': 155, 'Slovenia': 156, 'Solomon Islands': 157,
#     'Somalia': 158, 'South Africa': 159, 'South Korea': 160, 'South Sudan': 161,
#     'Spain': 162, 'Sri Lanka': 163, 'St. Vincent Grenadines': 164,
#     'State of Palestine': 165, 'Sudan': 166, 'Suriname': 167, 'Sweden': 168,
#     'Switzerland': 169, 'Syria': 170, 'Tajikistan': 171, 'Tanzania': 172,
#     'Thailand': 173, 'Timor-Leste': 174, 'Togo': 175, 'Tonga': 176,
#     'Trinidad and Tobago': 177, 'Tunisia': 178, 'Turkey': 179, 'Turkmenistan': 180,
#     'Tuvalu': 181, 'U.A.E': 182, 'U.K': 183, 'U.S': 184, 'Uganda': 185,
#     'Ukraine': 186, 'Uruguay': 187, 'Uzbekistan': 188, 'Vanuatu': 189,
#     'Venezuela': 190, 'Vietnam': 191, 'Yemen': 192, 'Zambia': 193, 'Zimbabwe': 194
# ]
class_indices = {
    'Afghanistan': 0, 'Albania': 1, 'Algeria': 2, 'Andorra': 3, 'Angola': 4,
    'Antigua and Barbuda': 5, 'Argentina': 6, 'Armenia': 7, 'Australia': 8,
    'Austria': 9, 'Azerbaijan': 10, 'Bahamas': 11, 'Bahrain': 12, 'Bangladesh': 13,
    'Barbados': 14, 'Belarus': 15, 'Belgium': 16, 'Belize': 17, 'Benin': 18,
    'Bhutan': 19, 'Bolivia': 20, 'Bosnia and Herzegovina': 21, 'Botswana': 22,
    'Brazil': 23, 'Brunei': 24, 'Bulgaria': 25, 'Burkina Faso': 26, 'Burundi': 27,
    'CAR': 28, 'Cabo Verde': 29, 'Cambodia': 30, 'Cameroon': 31, 'Canada': 32,
    'Chad': 33, 'Chile': 34, 'China': 35, 'Colombia': 36, 'Comoros': 37,
    'Congo': 38, 'Costa Rica': 39, 'Croatia': 40, 'Cuba': 41, 'Cyprus': 42,
    'Czechia': 43, 'DPRK': 44, 'DRC': 45, 'Denmark': 46, 'Djibouti': 47,
    'Dominica': 48, 'Dominican Republic': 49, 'Ecuador': 50, 'Egypt': 51,
    'El Salvador': 52, 'Equatorial Guinea': 53, 'Eritrea': 54, 'Estonia': 55,
    'Eswatini': 56, 'Ethiopia': 57, 'Fiji': 58, 'Finland': 59, 'France': 60,
    'Gabon': 61, 'Gambia': 62, 'Georgia': 63, 'Germany': 64, 'Ghana': 65,
    'Greece': 66, 'Grenada': 67, 'Guatemala': 68, 'Guinea': 69, 'Guinea-Bissau': 70,
    'Guyana': 71, 'Haiti': 72, 'Holy See': 73, 'Honduras': 74, 'Hungary': 75,
    'Iceland': 76, 'India': 77, 'Indonesia': 78, 'Iran': 79, 'Iraq': 80,
    'Ireland': 81, 'Israel': 82, 'Italy': 83, 'Ivory Coast': 84, 'Jamaica': 85,
    'Japan': 86, 'Jordan': 87, 'Kazakhstan': 88, 'Kenya': 89, 'Kiribati': 90,
    'Kuwait': 91, 'Kyrgyzstan': 92, 'Laos': 93, 'Latvia': 94, 'Lebanon': 95,
    'Lesotho': 96, 'Liberia': 97, 'Libya': 98, 'Liechtenstein': 99, 'Lithuania': 100,
    'Luxembourg': 101, 'Madagascar': 102, 'Malawi': 103, 'Malaysia': 104,
    'Maldives': 105, 'Mali': 106, 'Malta': 107, 'Marshall Islands': 108,
    'Mauritania': 109, 'Mauritius': 110, 'Mexico': 111, 'Micronesia': 112,
    'Moldova': 113, 'Monaco': 114, 'Mongolia': 115, 'Montenegro': 116,
    'Morocco': 117, 'Mozambique': 118, 'Myanmar': 119, 'Namibia': 120,
    'Nauru': 121, 'Nepal': 122, 'Netherlands': 123, 'New Zealand': 124,
    'Nicaragua': 125, 'Niger': 126, 'Nigeria': 127, 'North Macedonia': 128,
    'Norway': 129, 'Oman': 130, 'Pakistan': 131, 'Palau': 132, 'Panama': 133,
    'Papua New Guinea': 134, 'Paraguay': 135, 'Peru': 136, 'Philippines': 137,
    'Poland': 138, 'Portugal': 139, 'Qatar': 140, 'Romania': 141, 'Russia': 142,
    'Rwanda': 143, 'Saint Kitts and Nevis': 144, 'Saint Lucia': 145, 'Samoa': 146,
    'San Marino': 147, 'Sao Tome and Principe': 148, 'Saudi Arabia': 149,
    'Senegal': 150, 'Serbia': 151, 'Seychelles': 152, 'Sierra Leone': 153,
    'Singapore': 154, 'Slovakia': 155, 'Slovenia': 156, 'Solomon Islands': 157,
    'Somalia': 158, 'South Africa': 159, 'South Korea': 160, 'South Sudan': 161,
    'Spain': 162, 'Sri Lanka': 163, 'St. Vincent Grenadines': 164,
    'State of Palestine': 165, 'Sudan': 166, 'Suriname': 167, 'Sweden': 168,
    'Switzerland': 169, 'Syria': 170, 'Tajikistan': 171, 'Tanzania': 172,
    'Thailand': 173, 'Timor-Leste': 174, 'Togo': 175, 'Tonga': 176,
    'Trinidad and Tobago': 177, 'Tunisia': 178, 'Turkey': 179, 'Turkmenistan': 180,
    'Tuvalu': 181, 'U.A.E': 182, 'U.K': 183, 'U.S': 184, 'Uganda': 185,
    'Ukraine': 186, 'Uruguay': 187, 'Uzbekistan': 188, 'Vanuatu': 189,
    'Venezuela': 190, 'Vietnam': 191, 'Yemen': 192, 'Zambia': 193, 'Zimbabwe': 194
}
# Convert dict → list such that index gives class name
class_names = [None] * len(class_indices)
for name, idx in class_indices.items():
    class_names[idx] = name

def predict_flag(img_path, target_size=(224, 224)):
    img = image.load_img(img_path, target_size=target_size)
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    preds = model.predict(img_array)[0]

    # Best class selection
    class_index = np.argmax(preds)
    confidence = preds[class_index]

    print("Predicted Country:", class_names[class_index])
    print("Confidence:", round(float(confidence), 4))

# def predict(img):
#     # Resize image to model size
#     img = img.resize((224, 224))  # change size according to your model

#     img_array = tf.keras.utils.img_to_array(img)
#     img_array = np.expand_dims(img_array, axis=0)
#     img_array = img_array / 255.0  # normalize

#     pred = model.predict(img_array)
#     class_index = np.argmax(pred, axis=1)[0]
#     confidence = np.max(pred)

#     return {
#         "Predicted Class": class_names[class_index],
#         "Confidence": float(confidence)
#     }
def predict(img):
    # Resize image to model input size
    img = img.resize((224, 224))
    img_array = tf.keras.utils.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array / 255.0

    pred = model.predict(img_array)
    class_index = np.argmax(pred, axis=1)[0]

    return class_names[class_index]

# 5. Create Gradio UI
# ==========================================
import gradio as gr

interface = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil"),
    outputs="label",
    title="Flag Classification Model",
    description="Upload an image of a flag and get prediction from the trained model."
)

# ==========================================
# 6. Launch UI
# ==========================================
interface.launch(debug=True)

!pip install huggingface_hub --upgrade
!pip install gradio tensorflow numpy Pillow

from huggingface_hub import notebook_login

notebook_login()

import os
os.makedirs("Flag_Recognition_Model", exist_ok=True)

!cp /content/drive/MyDrive/final_flag_model.h5 Flag_Recognition_Model/model.h5

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Flag_Recognition_Model/app.py
# import gradio as gr
# import tensorflow as tf
# import numpy as np
# from PIL import Image
# 
# # Load model
# model = tf.keras.models.load_model("model.h5")
# 
# # Index to country mapping
# class_names = {
#     'Afghanistan': 0, 'Albania': 1, 'Algeria': 2, 'Andorra': 3, 'Angola': 4,
#     'Antigua and Barbuda': 5, 'Argentina': 6, 'Armenia': 7, 'Australia': 8,
#     'Austria': 9, 'Azerbaijan': 10, 'Bahamas': 11, 'Bahrain': 12, 'Bangladesh': 13,
#     'Barbados': 14, 'Belarus': 15, 'Belgium': 16, 'Belize': 17, 'Benin': 18,
#     'Bhutan': 19, 'Bolivia': 20, 'Bosnia and Herzegovina': 21, 'Botswana': 22,
#     'Brazil': 23, 'Brunei': 24, 'Bulgaria': 25, 'Burkina Faso': 26, 'Burundi': 27,
#     'CAR': 28, 'Cabo Verde': 29, 'Cambodia': 30, 'Cameroon': 31, 'Canada': 32,
#     'Chad': 33, 'Chile': 34, 'China': 35, 'Colombia': 36, 'Comoros': 37,
#     'Congo': 38, 'Costa Rica': 39, 'Croatia': 40, 'Cuba': 41, 'Cyprus': 42,
#     'Czechia': 43, 'DPRK': 44, 'DRC': 45, 'Denmark': 46, 'Djibouti': 47,
#     'Dominica': 48, 'Dominican Republic': 49, 'Ecuador': 50, 'Egypt': 51,
#     'El Salvador': 52, 'Equatorial Guinea': 53, 'Eritrea': 54, 'Estonia': 55,
#     'Eswatini': 56, 'Ethiopia': 57, 'Fiji': 58, 'Finland': 59, 'France': 60,
#     'Gabon': 61, 'Gambia': 62, 'Georgia': 63, 'Germany': 64, 'Ghana': 65,
#     'Greece': 66, 'Grenada': 67, 'Guatemala': 68, 'Guinea': 69, 'Guinea-Bissau': 70,
#     'Guyana': 71, 'Haiti': 72, 'Holy See': 73, 'Honduras': 74, 'Hungary': 75,
#     'Iceland': 76, 'India': 77, 'Indonesia': 78, 'Iran': 79, 'Iraq': 80,
#     'Ireland': 81, 'Israel': 82, 'Italy': 83, 'Ivory Coast': 84, 'Jamaica': 85,
#     'Japan': 86, 'Jordan': 87, 'Kazakhstan': 88, 'Kenya': 89, 'Kiribati': 90,
#     'Kuwait': 91, 'Kyrgyzstan': 92, 'Laos': 93, 'Latvia': 94, 'Lebanon': 95,
#     'Lesotho': 96, 'Liberia': 97, 'Libya': 98, 'Liechtenstein': 99, 'Lithuania': 100,
#     'Luxembourg': 101, 'Madagascar': 102, 'Malawi': 103, 'Malaysia': 104,
#     'Maldives': 105, 'Mali': 106, 'Malta': 107, 'Marshall Islands': 108,
#     'Mauritania': 109, 'Mauritius': 110, 'Mexico': 111, 'Micronesia': 112,
#     'Moldova': 113, 'Monaco': 114, 'Mongolia': 115, 'Montenegro': 116,
#     'Morocco': 117, 'Mozambique': 118, 'Myanmar': 119, 'Namibia': 120,
#     'Nauru': 121, 'Nepal': 122, 'Netherlands': 123, 'New Zealand': 124,
#     'Nicaragua': 125, 'Niger': 126, 'Nigeria': 127, 'North Macedonia': 128,
#     'Norway': 129, 'Oman': 130, 'Pakistan': 131, 'Palau': 132, 'Panama': 133,
#     'Papua New Guinea': 134, 'Paraguay': 135, 'Peru': 136, 'Philippines': 137,
#     'Poland': 138, 'Portugal': 139, 'Qatar': 140, 'Romania': 141, 'Russia': 142,
#     'Rwanda': 143, 'Saint Kitts and Nevis': 144, 'Saint Lucia': 145, 'Samoa': 146,
#     'San Marino': 147, 'Sao Tome and Principe': 148, 'Saudi Arabia': 149,
#     'Senegal': 150, 'Serbia': 151, 'Seychelles': 152, 'Sierra Leone': 153,
#     'Singapore': 154, 'Slovakia': 155, 'Slovenia': 156, 'Solomon Islands': 157,
#     'Somalia': 158, 'South Africa': 159, 'South Korea': 160, 'South Sudan': 161,
#     'Spain': 162, 'Sri Lanka': 163, 'St. Vincent Grenadines': 164,
#     'State of Palestine': 165, 'Sudan': 166, 'Suriname': 167, 'Sweden': 168,
#     'Switzerland': 169, 'Syria': 170, 'Tajikistan': 171, 'Tanzania': 172,
#     'Thailand': 173, 'Timor-Leste': 174, 'Togo': 175, 'Tonga': 176,
#     'Trinidad and Tobago': 177, 'Tunisia': 178, 'Turkey': 179, 'Turkmenistan': 180,
#     'Tuvalu': 181, 'U.A.E': 182, 'U.K': 183, 'U.S': 184, 'Uganda': 185,
#     'Ukraine': 186, 'Uruguay': 187, 'Uzbekistan': 188, 'Vanuatu': 189,
#     'Venezuela': 190, 'Vietnam': 191, 'Yemen': 192, 'Zambia': 193, 'Zimbabwe': 194
#  }  # your dictionary
# index_to_class = {v:k for k,v in class_names.items()}
# 
# def predict(img):
#     img = img.resize((224, 224))
#     img_array = tf.keras.utils.img_to_array(img)
#     img_array = np.expand_dims(img_array, axis=0) / 255.0
#     pred = model.predict(img_array)
#     class_index = np.argmax(pred, axis=1)[0]
#     return index_to_class[class_index]
# 
# demo = gr.Interface(
#     fn=predict,
#     inputs=gr.Image(type="pil"),
#     outputs="text",
#     title="Flag Classification Model",
#     description="Upload an image of a flag and get prediction from the trained model."
# )
# 
# demo.launch()
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Flag_Recognition_Model/requirements.txt
# tensorflow
# gradio
# numpy
# Pillow
#

# from huggingface_hub import Repository

# repo_url = "https://huggingface.co/spaces/highhuzaifa/Flag_Recognition_Model"
# repo = Repository(local_dir="Flag_Recognition_Model", clone_from=repo_url)

# repo.push_to_hub(commit_message="Initial commit from Colab")
!pip install huggingface_hub --upgrade

from huggingface_hub import notebook_login
notebook_login()

from huggingface_hub import HfApi

api = HfApi()

# Replace with your Space info
space_id = "highhuzaifa/Flag_Recognition_Model"

# Push all files in your local folder to the Space
api.upload_folder(
    folder_path="Flag_Recognition_Model",  # local folder containing app.py, model.h5, requirements.txt
    path_in_repo="",                        # keep empty to upload to root
    repo_id=space_id,
    repo_type="space",
    token=True                              # uses the token from notebook_login
)